INSERT INTO divergencias (descricao) VALUES
	 ('FORA DO PADRÃO DE QUALIDADE'),
	 ('PRODUTO FISICO DIFERENTE NOTA FISCAL'),
	 ('QUANTIDADE FISICA DIFERENTE NOTA FISCAL'),
	 ('QUANTIDADE FISICA DIFERENTE PEDIDO COMPRA'),
	 ('PRODUTO FISICO DIFERENTE PEDIDO DE COMPRA'),
	 ('EMBALAGENS AVARIADAS'),
	 ('PRODUTO PROXIMO DO VENCIMENTO 30 DIAS');
